### PR TITLE
Support watching directories

### PR DESCRIPTION
**Pull request by underdoeg**
Sometimes you want to know what is going on in a directory. This is missing the windows implementation.

### CODE REVIEW

**Comment by underdoeg** [comment]
ah great I also included the cmake changes by accident...

**Comment by underdoeg** [comment]
I think I'll change this to an additional directory_watcher interface with more directory related settings

**Comment by tgfrerer** [comment]
i'm a bit confused about what this PR does... it seems it's the same changes as #23 ?

**Comment by underdoeg** [comment]
oh great... sorry, I have too many branches and changes locally. I've added my changes on top

**Comment by tgfrerer** [comment]
oh i see... would you mind making this a separate PR (without the module changes) so that we can look an test it in isolation? 

that will also make it easier to add a windows implementation.

**Comment by underdoeg** [comment]
Will do, but I think, I'll approach it differently with a dedicated directory interface to avoid confusion

**Comment by tgfrerer** [comment]
Sounds good - shall we close this pr for now, then?

**Comment by underdoeg** [comment]
yes

**Pull request closed without merging**
